### ISSUE TITLE
problem in installing code

### ISSUE THREAD

**Issue by SHAILJA0** [lewisfish/RayTran#1]
Hii

Thank you for putting this code and much effort you put it in. I am a starter in raytracing and came through this code. I wanted to understand its working but not able to install it. While trying to install with install.sh file , It is asking for utils module which i got in main.f90 as a module encoded . Then I tried to compile src/main.f90 file first but it is again asking mpi_f08.mod file which is not there in downloaded code folder .

Please provide your suggestion what I can do to make work it.

regards
Shailja
![error](https://user-images.githubusercontent.com/35450290/88253334-2b00f100-cccf-11ea-8abe-3ce5d633eafe.JPG)

**Comment by lewisfish** [comment]
Hi Shailja, 
The code requires that a version of MPI which supports Fortran 2008 be installed. OpenMPI can be downloaded from [here](https://www.open-mpi.org/)
It uses MPI to parallelise the code.
I wouldn't recommend using my code if you are just learning raytracing, but rather the code it is based upon https://raytracing.github.io/books/RayTracingInOneWeekend.html

**Comment by SHAILJA0** [comment]
Thank you very much !!!
